user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost;

        # The volume mounts catalog_images to /usr/share/nginx/html/catalog
        # so any request to /catalog/... will match this alias
        location /catalog/ {
            alias /usr/share/nginx/html/catalog/;
            add_header 'Access-Control-Allow-Origin' '*';
            expires max;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
        
        # Opcionalmente, para servir desde la ruta base de imágenes directamente
        location /images/ {
            alias /usr/share/nginx/html/catalog/;
            add_header 'Access-Control-Allow-Origin' '*';
            expires max;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
